# Generated by Django 3.0.5 on 2022-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Solapur', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(default='Solapur', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Island', 'Andaman & Nicobar Island'), ('Solapur', 'Solapur'), ('Vijapur', 'Vijapur'), ('Suregaon', 'Suregaon')], default='Solapur', max_length=50, null=True),
        ),
    ]
